ruby/rubysoho/config/routes.rb
Rails.application.routes.draw do

  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments
  end
end

ruby/rubysoho/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby/rubysoho/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

ruby/rubysoho/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
end

ruby/rubysoho/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby/rubysoho/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "ccrsh", password: "secret", only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destory
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_patch(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

ruby/rubysoho/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
      @title = 'About us';
    end
end

ruby/rubysoho/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "ccrsh", password: "secret", except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

ruby/rubysoho/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/rubysoho/app/helpers/comments_helper.rb
module CommentsHelper
end

ruby/rubysoho/app/helpers/pages_helper.rb
module PagesHelper
end

ruby/rubysoho/app/helpers/posts_helper.rb
module PostsHelper
end

ruby/rubysoho/app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
  <div class="well">
    <p>
      <strong><%= comment.username %></strong>: <%= comment.body %>
    </p>
    <%= link_to 'Delete',
        [comment.post, comment],
        method: :delete,
        data: { confirm: 'Are you sure?' }
    %>
  </div>
<% end %>

ruby/rubysoho/app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field( :username, {:class => 'form-control'}) %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area( :body, {:class => 'form-control'}) %>
  </div>

  <%= f.submit({:class => 'btn btn-info'}) %>
<% end %>

ruby/rubysoho/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby Soho</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", home_path, {:class => 'nav-link'} %>
          </li>
          <li class="nav-item">
            <%= link_to "Create Post", new_post_path, {:class => 'nav-link'} %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

ruby/rubysoho/app/views/pages/about.html.erb
<h1><%= @title %></h1>

ruby/rubysoho/app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <br />
    <%= f.text_field( :title, {:class => 'form-control is valid'}) %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <br />
    <%= f.text_area( :body, {:class => 'form-control'}) %>
  </div>

    <%= f.submit({:class => 'btn btn-info'}) %>
<% end %>

ruby/rubysoho/app/views/posts/index.html.erb
<h1>All posts</h1>

<% @posts.each do |post| %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text"><%= post.body %></p>
      <%= link_to "Read More", post_path(post), :class => 'btn btn-info' %>
    </div>
  </div>
<% end %>

ruby/rubysoho/app/views/posts/new.html.erb
<h1>Add post</h1>
<%= form_for :post, url: posts_path do |f| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  
  <div class="form-group">
    <%= f.label :title %>
    <br />
    <%= f.text_field( :title, {:class => 'form-control is valid'}) %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <br />
    <%= f.text_area( :body, {:class => 'form-control'}) %>
  </div>

    <%= f.submit({:class => 'btn btn-info'}) %>
<% end %>

ruby/rubysoho/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>

<hr />

<%= link_to "Edit",
  edit_post_path(@post),
  :class => 'btn btn-info'
%>
<%= link_to "Delete",
  post_path(@post),
  method: :delete,
  data: {confirm: 'Are you sure?'},
  :class => 'btn btn-danger'
%>

<hr />

<%= render 'comments/comments' %>
<%= render 'comments/form' %>